# Generated by Django 5.2.9 on 2026-03-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_like_match'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='match',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user2',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
